main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name = 'index'),
    # path('aboutus', views.aboutus, name = 'aboutus'),
    # path('contacts', views.contacts, name = 'contacts'),
    # path('web_dev', views.web_dev, name = 'web_dev'),
    # path('design', views.design, name = 'design'),
    # path('adv', views.adv, name = 'adv'),
    path('call_request', views.call_request, name = 'call_request'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length = 500, default = None, 
    blank = True, null = True)
    priority = models.IntegerField(default = 0,)

    def __str__(self):
        if self.name:
            return self.name
        else:
            return 'no name specified' 
    

class CategoryImage(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    imgsrc = models.ImageField(upload_to = 'static/images/categories')

main/views.py
from django.shortcuts import render
from .models import * 
from django.http import JsonResponse, HttpResponse
import urllib
import os
from django.core.files.storage import default_storage
from mysite.settings import * 
import json
from django.template.loader import render_to_string
from datetime import datetime
# from .telegrambot import *
from .viberbot import * 

# Create your views here.

def index(request):
    categories = Category.objects.all()
    template = 'main/index.html'
    context = {
        'categories': categories
    }
    return  render(request, template, context)

def aboutus(request):
    template = 'main/aboutus.html'
    context = {

    }
    return render(request, template, context)

def contacts(request):
    template = 'main/contacts.html'
    context = {

    }
    return render(request, template, context)
    

def web_dev(request):
    template = 'main/web_dev.html'
    context = {

    }
    return render(request, template, context)

def design(request):
    template = 'main/design.html'
    context = {
        
    }
    return render(request, template, context)

def adv(request):
    template = 'main/adv.html'
    context = {
        
    }
    return render(request, template, context)
    
    
def call_request(request):
    time = datetime.now()
    time = time.strftime("%Y-%m-%d-%H:%M")
    current_time = f'Время заявки: {time} \n'
    call_name = request.GET['call_name']
    call_phone = request.GET['call_phone']
    call_about = request.GET['call_about']
    final_message =  '🔥 Заявка на обратный звонок 🔥 \n' + 'Сайт: lena photo \n' + f'Имя: {call_name} \n' + f'Телефон: {call_phone} \n' + f'Съемка: {call_about} \n' + current_time
    send_viber_message(final_message)
    return JsonResponse({
        'send': True,
    }, status = 200)
    

templates/main/aboutus.html
{% extends './base.html' %}
{% load static %}

{% block content %}

    <div class="aboutus_wrapper">

    <div class="page__header__container">
        <img class="page__header__container__img" 
        src="{% static 'images/about_bg.jpg' %}" alt="">
        <div class="page__header__container__bg">
        </div>
        <div class="page__header__container__title">
            <span>
                о нас
            </span>
        </div>
    </div>

    </div>

    {% include './blocks/we_can.html' %}

    {% include './blocks/serv_container.html' %}

    <div class="benefits_container">
        <div class="benefits_container_info">
            <div class="nice_title2 center benefits_container__title">
            <span>
                Стратегия
            </span>
            </div>
            <div class="benefits_container_info_list">
                <div class="benefits_container_info_item">
                    <div class="benefits_container_info_item__title">
                        <i class="fa fa-atom"></i>
                        <span>
                            Качественная и гибкая разработка
                        </span>
                    </div>
                    {% comment %} <div class="benefits_container_info_item__desc">
                        Выделенные проектные группы
                    </div> {% endcomment %}
                </div>
                <div class="benefits_container_info_item">
                    <div class="benefits_container_info_item__title">
                        <i class="fa fa-atom"></i>
                        <span>
                        Современные и надежные технологии
                        </span>
                    </div>
                </div>
                <div class="benefits_container_info_item">
                    <div class="benefits_container_info_item__title">
                        <i class="fa fa-atom"></i>
                        <span>
                            Персональный подход к каждому клиенту
                        </span>
                    </div>
                </div>
                <div class="benefits_container_info_item">
                    <div class="benefits_container_info_item__title">
                        <i class="fa fa-atom"></i>
                        <span>
                        Выделенные проектные группы
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include './blocks/request_call.html' %}

{% endblock content %}

templates/main/adv.html
{% extends './base.html' %}
{% load static %}

{% block content %}

    
<div class="case-main dark case-main-top">
    <div class="case-main-text design-header-title">
        <h3 class="case-main__title case-f aos-init aos-animate" data-aos="fade-down">
            {% block intro__container__title %}
                Реклама вашего бизнеса
            {% endblock intro__container__title %}
        </h3>
        <div class="case-main__subtitle">
            Google, Yandex <br>
            Facebook, VK<br>
        </div>
        <p class="case-main__desc aos-init aos-animate" data-aos="fade-down" data-aos-delay="150">
        </p>
    </div>
    <div class="case-main-img-wrapper">
        <noscript><img data-aos-anchor=".case-main__title" data-aos-duration="700" data-aos="fade-left" data-aos-delay="250" 
            src="{% static 'images/adv_main2.png' %}" alt=""></noscript>
        <img class="aos-init lazyloaded aos-animate" data-aos-anchor=".case-main__title" data-aos-duration="700" data-aos="fade-left" data-aos-delay="250" src="{% static 'images/adv_main2.png' %}" data-src="{% static 'images/adv_main2.png' %}" alt="">
    </div>
</div>

{% comment %} sale container  {% endcomment %}
    <div class="sale__container">
        <img class="sale__container__img"
        src="{% static 'images/sale_container_bg.png' %}" alt="">
        <div class="sale__container__bg">
        </div>
        <div class="sale__container__title">
            Дизайн в подарок при заказе сайта
        </div>
        <div class="nice_button sale__container__button">
            <span>
                Узнать больше
            </span>
        </div>
    </div>
{% comment %}  end sale container {% endcomment %}


    {% comment %} benefits container {% endcomment %}
    <div class="benefits__wrapper">
        <div class="nice_title2 center">
            <span>
                Зачем нужна настройка рекламы
            </span>
        </div>
        <div class="benefits">
            <div class="benefits__image">
                <img src="{% static 'images/adv_main3.png' %}" alt="">
            </div>
            <div class="benefits__items">
                <div class="benefits__items__item">
                    <i class="fa fa-chevron-right"></i>
                    <span>
                        Вас увидят в поисковиках, мобильных приложениях, YouTube, в ленте и сообществах Вконтакте
                    </span>
                </div>
                <div class="benefits__items__item">
                    <i class="fa fa-chevron-right"></i>
                    <span>
                        Только целевая аудитория. Реклама будет показываться пользователям, которые ищут ваш товар или заинтересованы в нем.
                    </span>
                </div>
                <div class="benefits__items__item">
                    <i class="fa fa-chevron-right"></i>
                    <span>
                        Постоянный рост эффективности. Каждый месяц мы анализируем результаты и перераспределяем бюджет в пользу работающих решений.
                    </span>
                </div>
                <div class="benefits__items__item">
                    <i class="fa fa-chevron-right"></i>
                    <span>
                        Платите за результат. Вы платите только когда пользователь переходит на сайт или звонит вам.
                    </span>
                </div>
            </div>
        </div>
    </div>
    {% comment %} end benefits container {% endcomment %}


    {% include './blocks/request_call.html' %}

    {% include './blocks/contacts_container.html' %}
    

{% endblock content %}

templates/main/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:image" content="{% static 'images/logo_main_black.png' %}" />
    <title>Фотограф Елена Федоренко</title>
</head>
<body>

{% include './includes_css.html' %}
{% include './includes_js.html' %}



{% block header %}
    <div class="main__header__block__wrapper">
        <div class="main__header__block">
            {% include './blocks/header.html' %}
        </div>
    </div>

{% endblock header %}


{% block content %}
{% endblock content %}

    {% comment %} {% include './blocks/footer.html' %} {% endcomment %}

    {% include './blocks/popup_complete.html' %}


</body>

<script>
  
function sendCall(call_type) {
    console.log('button is clicked')
    console.log(call_type)
    if (call_type == 'project') {
        var call_name = $("input[name='call_name']").val()
        var call_phone = $("input[name='call_phone']").val()
        var call_about = $("input[name='call_about']").val()
        $.ajax({
            url: "{% url 'main:call_request' %}",
            data: {
                'call_type': call_type,
                'call_name': call_name,
                'call_phone': call_phone,
                'call_about': call_about,
            }, success: function(data) {
                openThankPopup()
            }
        });
    }
    if (call_type == 'phone_only') {
        var call_phone = $("input[name='call_phone2']").val()
        $.ajax({
            url: "{% url 'main:call_request' %}",
            data: {
                'call_type': call_type,
                'call_phone': call_phone,
            }, success: function(data) {
                openThankPopup()
            }
        });
    }
}

function checkForm(call_type) {
    var passed = true
    if (call_type == 'project') {
        var call_name = $("input[name = 'call_name']")
        var call_phone = $("input[name = 'call_phone']")
        if ($(call_name).val().length < 1) {
            $(call_name).addClass('alert')
            passed = false
        } else {
            $(call_name).removeClass('alert')
        }
        if ($(call_phone).val().length < 1) {
            $(call_phone).addClass('alert')
            passed = false
        } else {
            $(call_phone).removeClass('alert')
        }
        return passed
    }
    if (call_type == 'phone_only') {
        var call_phone = $("input[name = 'call_phone2']")
        if ($(call_phone).val().length < 1) {
            $(call_phone).addClass('alert')
            passed = false
        } else {
            $(call_phone).removeClass('alert')
        }
        return passed
    }
}
function openThankPopup() { 
    $("#thank_popup").addClass("show")
    $(".contacts_popup_bg").addClass("show")
}
function closeThankPopup() { 
    $("#thank_popup").removeClass("show")
    $(".contacts_popup_bg").removeClass("show")
}

$('#send_call_phone').click(function() {
    var call_type = 'project'
    var passed = checkForm(call_type)
    if (passed == true) {
        sendCall(call_type)
    }
})

$('#send_call_phone2').click(function() {
    var call_type = 'phone_only'
    var passed = checkForm(call_type)
    if (passed == true) {
        sendCall(call_type)
    }
})

$('#thank_popup_close').click(function() {
    closeThankPopup()
})




</script>

</html>

templates/main/blocks/header.html
<!-- {% include './h_first.html' %} -->
{% load static %}




<div class="main__header__second">
    

    <div class="header__second__catalog">
        <div class="header__second__catalog__items">
            <a href="{% url 'main:index' %}#about_me_anchor">
                обо мне
            </a>
        </div>
        <div class="header__second__catalog__items">
            <a
            href="{% url 'main:index' %}#services_anchor">
                услуги
            </a>
        </div>
        <div class="header__second__catalog__items">
            <a
            href="{% url 'main:index' %}#prices_anchor">
                цены
            </a>
        </div>
        <div class="header__second__catalog__items">
            <a
            href="{% url 'main:index' %}#contacts_anchor">
                контакты
            </a>
        </div>
        <div class="header__second__catalog__items">
            <a
            href="{% url 'main:index' %}#requestcall_anchor">
                записаться
            </a>
        </div>
        
    </div>

    <!-- <div class="main__header__phone">
        <i class="fa fa-phone-alt
        contact_with_us_icon"></i>
        <div class="main__header__phone__callme">
            <div class="main__header__phone__callme callme_link contact_title">
                Связаться с нами
            </div> 
            <span class="contact_with_us_phone">
                +7(978)-221-55-09
            </span>
        </div>
    </div> -->

    <div class="header__second__catalog__mobile__wrapper">
    <span class="header__second__catalog__mobile">
        <div class="header__second__catalog__mobile__items">
        <i class="gg-menu-left-alt"></i> 
        </div>
    </span>
    </div>    

    <div class="main__header__phone__mobile">
        <!-- <div class="main__header__phone__main">
            <i class="fa fa-phone-alt"></i>
            <div class="main__header__phone__main__text">
                <a href="tel:+79781161415">
                    +7 (978) 116-14-15
                </a>
            </div>
        </div> -->
        <!-- <div class="main__header__phone__callme">
            <span class="main__header__phone__callme callme_link">
                Заказать звонок
            </span>
        </div>
    </div> -->

    <!-- <div class="main__header__phone"> -->
        <i class="fa fa-phone-alt
        contact_with_us_icon"></i>
        <div class="main__header__phone__callme">
            <div class="main__header__phone__callme callme_link contact_title">
                <a href="tel:+79788705075"
                class="call_link2">
                    Связаться со мной
                </a>
            </div> 
            <a href="tel:+79788705075"
            class="contact_with_us_phone call_link2">
            +7(978) 870 50 75
            </a>
        </div>
    <!-- </div> -->


    <div class="header__second__icons">



        <!-- <a class="header__second__icons__item account__big">
            <svg height="24" viewBox="0 0 20 20" width="24"><path d="M16.984 14.506V17H3.016v-2.494C4.47 11.794 6.797 10.438 10 10.438s5.531 1.356 6.984 4.068zM10 11.938c-2.528 0-4.295.958-5.484 2.961v.6h10.968v-.6c-1.19-2.003-2.956-2.961-5.484-2.961zm3.686-6.384a3.686 3.686 0 11-7.372 0 3.686 3.686 0 017.372 0zm-1.5 0a2.186 2.186 0 10-4.372 0 2.186 2.186 0 004.372 0z"></path></svg>
        </a> -->

    </div>
</div>


<div class="header__popup__mobile">
    <div class="header__popup__mobile__menu">
        <a href="{% url 'main:index' %}#about_me_anchor"
            class="mobile__nav">
                Обо мне
            </a>
            <a href="{% url 'main:index' %}#services_anchor"
            class="mobile__nav">
                Услуги
            </a>
            <a
            href="{% url 'main:index' %}#prices_anchor"
            class="mobile__nav">
                Цены
            </a>
            <a
            href="{% url 'main:index' %}#contacts_anchor"
            class="mobile__nav">
                Контакты
            </a>
            <a
            href="{% url 'main:index' %}#requestcall_anchor"
            class="mobile__nav">
                Записаться
            </a>
    </div>
</div>
<div class="header__popub__mobile__close">
    <i class="fa fa-close"></i>
</div>
<div class="header__popup__mobile__wrapper">

</div>



<script>
    // $(".header__second__catalog").click(function() {
    //     $(".catalog_open").toggleClass("hide")
    //     $(".catalog_close").toggleClass("show")
    //     $(".header__second__catalog").toggleClass("opened")
    //     $(".header__second__catalog__items").toggleClass("opened")
    // })
    $(".header__second__catalog__mobile").click(function() {
        openMobileMenu()
    })
    $(".header__popub__mobile__close").click(function() {
        closeMobileMenu()
    })
    $(".mobile__nav").click(function() {
        closeMobileMenu()
    })


    function openMobileMenu() {
            $(".header__popup__mobile").addClass("show")
            $(".header__popub__mobile__close").addClass("show")
            $("body").addClass("hidden")
        }
    function closeMobileMenu() {
            $(".header__popup__mobile").removeClass("show")
            $(".header__popub__mobile__close").removeClass("show")
            $("body").removeClass("hidden")
        }
</script>

templates/main/blocks/prices.html
{% load static %}
<div class="prices_container">
    <div class="nice_title2 center">
        <span>
            Цены    
        </span>
    </div>
    <div class="prices_item">
        <div class="prices_info">
            <div class="prices_info__title">
                <span>
                    Пакет "МИНИМАЛЬНЫЙ"
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    30 минут съёмка
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    10 лучших фотографий в авторской обработке с детальной ретушью
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    все удачные снимки в JPG формате (без обработки) 
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    помощь в позировании, подборе локации и образов
                </span>
            </div>
            <div class="item_price">
                <span>
                    2,000 руб.
                </span>
            </div>
            <div class="price_item_button nice_button margin_40">
                <a
                href="{% url 'main:index' %}#requestcall_anchor">
                    заказать
                </a>
            </div>
        </div>
        <div class="prices_img">
            <img src="{% static 'images/detskaya/4.jpg' %}" alt="">
        </div>
    </div>
    <div class="prices_item">
        <div class="prices_info">
            <div class="prices_info__title">
                <span>
                    Пакет "ОПТИМАЛЬНЫЙ" 
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    1 час съёмка
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    20 лучших фотографий в авторской обработке с детальной ретушью
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    все удачные снимки в JPG формате (без обработки) 
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    помощь в позировании, подборе места съёмки и образов
                </span>
            </div>
            <div class="item_price">
                <span>
                    3,500 руб.
                </span>
            </div>
            <div class="price_item_button nice_button margin_40">
                <a href="{% url 'main:index' %}#requestcall_anchor">
                    заказать
                </a>
            </div>
        </div>
        <div class="prices_img">
            <img src="{% static 'images/portrait/7.jpg' %}" alt="">
        </div>
    </div>
    <div class="prices_item">
        <div class="prices_info">
            <div class="prices_info__title">
                <span>
                    Пакет "МАКСИМАЛЬНЫЙ"
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    1 час съёмка 
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    20 лучших фотографий в авторской обработке с детальной ретушью 
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    все удачные снимки в цвето- и светокоррекции
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    помощь в позировании, подборе места съёмки и образов 
                </span>
            </div>
            <div class="item_price">
                <span>
                    5,500 руб.
                </span>
            </div>
            <div class="price_item_button nice_button margin_40">
                <a href="{% url 'main:index' %}#requestcall_anchor">
                    заказать
                </a>
            </div>
        </div>
        <div class="prices_img">
            <img src="{% static 'images/family/6.jpg' %}" alt="">
        </div>
    </div>
    {% comment %} <div class="prices_item">
        <div class="prices_info">
            <div class="prices_info__title">
                <span>
                    Пакет "VIP" (все включено) 
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    1 час съёмка 
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    20 лучших фотографий в авторской обработке с детальной ретушью 
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    аренда платья 
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    услуги визажиста (макияж, прическа) 
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    все удачные снимки в цвето- и  светокоррекции 
                </span>
            </div>
            <div class="prices_info_detail">
                <i class="fa fa-check-circle"></i>
                <span>
                    помощь в позировании, выборе места съёмки и образов
                </span>
            </div>
            <div class="item_price">
                <span>
                    8000 руб.
                </span>
            </div>
            <div class="price_item_button nice_button margin_40">
                <a href="{% url 'main:index' %}#requestcall_anchor">
                    заказать
                </a>
            </div>
        </div>
        <div class="prices_img">
            <img src="{% static 'images/portrait/7.jpg' %}" alt="">
        </div>
    </div> {% endcomment %}
    
</div>

templates/main/blocks/serv_container.html
{% load static %}
<div class="serv_container_wrapper">
    <div class="serv_container">
        <div class="serv_container_item">
            <img class="serv_container_item__image"
            src="{% static 'images/detskaya/1.jpg' %}" alt="">
            <div class="serv_container_item__bg">
            </div>
            <div class="serv_container_item__info">
                <div class="serv_container_item__info__title">
                    <span class="">
                        Детская фотосъёмка 
                    </span>
                </div>
                <div class="serv_container_item__info__desc">
                   
                    <div class="serv_container_item__info__button nice_button">
                        <a href="{% url 'main:index' %}#requestcall_anchor">
                        Заказать
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="serv_container_item">
        <img class="serv_container_item__image"
            src="{% static 'images/family/1.jpg' %}" alt="">
        <div class="serv_container_item__bg">
        </div>
            <div class="serv_container_item__info">
                <div class="serv_container_item__info__title">
                    <span>
                        Семейная фотосессия
                    </span>
                </div>
                <div class="serv_container_item__info__desc">
                    <div class="serv_container_item__info__button nice_button">
                        <a href="{% url 'main:index' %}#requestcall_anchor">
                        Заказать
                        </a>
                    </div>

                </div>

            </div>
        </div>
        <div class="serv_container_item">
        <img class="serv_container_item__image"
            src="{% static 'images/beremennost/1.jpg' %}" alt="">
        <div class="serv_container_item__bg">
        </div>
            <div class="serv_container_item__info">
                <div class="serv_container_item__info__title">
                    <span>
                        Фотосессия беременности
                    </span>
                </div>
                <div class="serv_container_item__info__desc">
                    <div class="serv_container_item__info__button nice_button">
                        <a href="{% url 'main:index' %}#requestcall_anchor">
                        Заказать
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="serv_container_item">
        <img class="serv_container_item__image"
            src="{% static 'images/portrait/1.jpg' %}" alt="">
        <div class="serv_container_item__bg">
        </div>
            <div class="serv_container_item__info">
                <div class="serv_container_item__info__title">
                    <span>
                        Портретная съёмка
                    </span>
                </div>
                <div class="serv_container_item__info__desc">
                    <div class="serv_container_item__info__button nice_button">
                        <a href="{% url 'main:index' %}#requestcall_anchor">
                        Заказать
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(".serv_container_item").hover(function() {
        
        $(this).addClass("hover")
        // var item = $(this).find(".serv_container_item__info__title span").addClass('underline ')
        console.log(item)
    }, function() {
        $(this).removeClass("hover")
        var item = $(this).find(".serv_container_item__info__title span").attr('class', '')
    })
</script>

templates/main/blocks/serv_container2.html
{% load static %}

{% for category in categories %}

<div class="nice_title2 center"
    style="padding:40 0;">
        <span>
            {{ category.name }}
        </span>
</div>

<div class="main_slider owl-theme owl-carousel">
    {% for img in category.categoryimage_set.all  %}
    <div class="slider_item">
        <img src="{{ img.imgsrc.url }}" alt="">
    </div>
    {% endfor %}
</div>

{% endfor %}
{% comment %} 
<div class="nice_title2 center"
    style="padding:40 0;">
        <span>
            Детская фотосъемка
        </span>
</div>
<div class="main_slider owl-theme owl-carousel">
    <div class="slider_item">
        <img src="{% static 'images/detskaya/8.jpg' %}" alt="">
    </div>
    <div class="slider_item">
        <img src="{% static 'images/detskaya/3.jpg' %}" alt="">
    </div>
    <div class="slider_item">
        <img src="{% static 'images/detskaya/4.jpg' %}" alt="">
    </div>
    <div class="slider_item">
        <img src="{% static 'images/detskaya/2.jpg' %}" alt="">
    </div>
</div>


<div class="nice_title2 center"
    style="padding:40 0;">
        <span>
            Семейная фотосессия
        </span>
</div>
<div class="main_slider owl-theme owl-carousel">
    <div class="slider_item">
        <img src="{% static 'images/family/1.jpg' %}" alt="">
    </div>
    <div class="slider_item">
        <img src="{% static 'images/family/4.jpg' %}" alt="">
    </div>
    <div class="slider_item">
        <img src="{% static 'images/family/6.jpg' %}" alt="">
    </div>
</div>

<div class="nice_title2 center"
    style="padding:40 0;">
        <span>
            Фотосессия беременности
        </span>
</div>
<div class="main_slider owl-theme owl-carousel">
    <div class="slider_item">
        <img src="{% static 'images/beremennost/2.jpg' %}" alt="">
    </div>
    <div class="slider_item">
        <img src="{% static 'images/beremennost/3.png' %}" alt="">
    </div>
    <div class="slider_item">
        <img src="{% static 'images/beremennost/5.jpg' %}" alt="">
    </div>
</div>

<div class="nice_title2 center"
    style="padding:40 0;">
        <span>
            Портретная съемка
        </span>
</div>
<div class="main_slider owl-theme owl-carousel">
    <div class="slider_item">
        <img src="{% static 'images/portrait/1.jpg' %}" alt="">
    </div>
    <div class="slider_item">
        <img src="{% static 'images/portrait/2.jpg' %}" alt="">
    </div>
    <div class="slider_item">
        <img src="{% static 'images/portrait/5.jpg' %}" alt="">
    </div>
</div> {% endcomment %}

templates/main/blocks/services2.html
{% include './services.html' %}

templates/main/contacts.html
{% extends './base.html' %}

{% block content %}

    {% include './blocks/contacts_container.html' %}

{% endblock content %}